<a href="https://colab.research.google.com/github/sarbanibhadra/Project_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of tensors with tensorflow
* Introduction to tensor
* Gathering information about tensors
* Manipulating tensors
* Learning about @tf.function() - a way to speed up python functions
* tensors and numPy
* Examples of tensors



Import tensorflow and print version

In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
# Create a tensor
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scaler.ndim

0

In [8]:
# Create a vector tensor
vector = tf.constant([1,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [7]:
vector.ndim

1

In [13]:
# Create a matrix
matrix = tf.constant([[1,7],[7,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [7, 8]], dtype=int32)>

In [19]:
# Create a tensor
tensor = tf.constant([[[1.0,3],[7,8]],
                      [[3,4],[6,3]],[[4,6],[5,8]] ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 3.],
        [7., 8.]],

       [[3., 4.],
        [6., 3.]],

       [[4., 6.],
        [5., 8.]]], dtype=float32)>

In [20]:
tensor.ndim

3