<a href="https://colab.research.google.com/github/sarbanibhadra/Project_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of tensors with tensorflow
* Introduction to tensor
* Gathering information about tensors
* Manipulating tensors
* Learning about @tf.function() - a way to speed up python functions
* tensors and numPy
* Examples of tensors



Import tensorflow and print version

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# Create a tensor
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scaler.ndim

0

In [ ]:
# Create a vector tensor
vector = tf.constant([1,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[1,7],[7,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [7, 8]], dtype=int32)>

In [ ]:
# Create a tensor
tensor = tf.constant([[[1.0,3],[7,8]],
                      [[3,4],[6,3]],[[4,6],[5,8]] ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 3.],
        [7., 8.]],

       [[3., 4.],
        [6., 3.]],

       [[4., 6.],
        [5., 8.]]], dtype=float32)>

In [ ]:
tensor.ndim

3

In [ ]:
# Creating tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(45)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([45,  7], dtype=int32)>

In [ ]:
# Creating two randon tensors
random_1 = tf.random.Generator.from_seed(41)
random_1 = random_1.normal(shape=(3,4))
random_2 = tf.random.Generator.from_seed(41)
random_2= random_2.normal(shape=(3,4))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape=(4,5))
random_4 = tf.random.Generator.from_seed(7)
random_4 = random_4.normal(shape=(4,5))
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape=(4,5))
random_4 = tf.random.Generator.from_seed(7)
random_4 = random_4.normal(shape=(4,5))
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644],
        [ 0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
        [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002],
        [ 1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>)

### Shuffle a tensor



In [ ]:
unshuffle_tensor = tf.constant([[7,5],
                                [6,9],
                                [8,3]])
unshuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 5],
       [6, 9],
       [8, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(5) #global level random seed
tf.random.shuffle(unshuffle_tensor, seed=5) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 9],
       [8, 3],
       [7, 5]], dtype=int32)>

# Other ways to create tensors

In [ ]:
# Create tensors of ones
ones = tf.ones([7,8])
ones

<tf.Tensor: shape=(7, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create tensors of zeros
zeros = tf.zeros(shape=(7,8), dtype=tf.int32)
zeros

<tf.Tensor: shape=(7, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

# Turn numpy arrays into tensors

In [ ]:
# The main difference between tensors and numpy arrays is tensors can run on GPU
import numpy as np
numpy_1 = np.arange(1,25)
numpy_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
numpy_tensor = tf.constant(numpy_1, shape=(1, 2,2,2,3))
numpy_tensor

<tf.Tensor: shape=(1, 2, 2, 2, 3), dtype=int64, numpy=
array([[[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]]])>

# Getting information from Tensors
* shape: Number of elements in each dimension
* rank: Number of dimensions
* axis or dimension: Each dimension
* size: Total number of elements


In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5), dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
# shape
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# rank
rank_4_tensor.ndim

4

In [ ]:
# axis or dimension
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [ ]:
# size
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

# Indexing with Tensors

In [ ]:
rank_4_tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
# Add an extra dimension to tensor
rank_5_tensor = rank_4_tensor[..., tf.newaxis]
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=int32, numpy=
array([[[[[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]],

         [[0],
          [0],
          [0],
          [0],
          [0]]]],



       [[[[0]

In [ ]:
rank_2_tensor = tf.constant([[6,7], [8,9]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[6, 7],
        [8, 9]]], dtype=int32)>

# TensorFlow multiplication

In [ ]:
x = tf.constant([[4,5],
                 [8,5]])
x * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 50],
       [80, 50]], dtype=int32)>

In [ ]:
y = tf.constant([[5,6],
                 [4,2]])
x * y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [32, 10]], dtype=int32)>

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 34],
       [60, 58]], dtype=int32)>

# Changing the datatype of tensors

In [ ]:
c = tf.constant([[6,7],
                [4,5]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5]], dtype=int32)>

In [ ]:
d = tf.cast(c, dtype=tf.float16) # reduce precison
d

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[6., 7.],
       [4., 5.]], dtype=float16)>

# Find tensorflow variance and standar deviation

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tf.__version__

'2.19.0'

In [ ]:
E = tf.random.Generator.from_seed(6)
E = tf.abs(tf.cast(10*E.normal(shape=(6,8)), dtype=tf.int32))
tf.reduce_max(E)
tfp.stats.variance(E)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 7, 10, 21, 19, 26,  4, 22,  4], dtype=int32)>

Finding variance using tf.math

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=16.78775978088379>

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
assert tf.reduce_max(F) == F[tf.argmax(F)]


In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeezing a tensor

In [59]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [60]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [61]:
G_squeezed = tf.squeeze(G)
G_squeezed, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [69]:
### One hot_encoding

indices = [0,1,2,3,4]
tf.one_hot(indices, depth=5, on_value="Ma", off_value="Baba")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Ma', b'Baba', b'Baba', b'Baba', b'Baba'],
       [b'Baba', b'Ma', b'Baba', b'Baba', b'Baba'],
       [b'Baba', b'Baba', b'Ma', b'Baba', b'Baba'],
       [b'Baba', b'Baba', b'Baba', b'Ma', b'Baba'],
       [b'Baba', b'Baba', b'Baba', b'Baba', b'Ma']], dtype=object)>